### ISSUE TITLE
[Bug] Link to Kaggle kernel is broken

### ISSUE THREAD

**Issue by ArthDh** [iridiumblue/roc-star#1]
Link to Kaggle Kernel in broken in README.md, any updated implementations?

**Comment by iridiumblue** [comment]
Ah, I have to make a few updates to the README.   Meanwhile, here's the working impl. : 
https://www.kaggle.com/iridiumblue/roc-star-an-auc-loss-function-to-challenge-bxe

**Comment by iridiumblue** [comment]
README.md updated
